- name: Copy repo file
  ansible.builtin.copy:
   src: mongo.repo
   dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongo
  ansible.builtin.dnf:
    name: mongodb-org
    state: installed

- name: Edit and set 12.0.0.0 to 0.0.0.0 in mongod.conf
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: 127.0.0.1
    replace: 0.0.0.0

- name: Enable and start mongod service
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: yes
